{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/localserver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/localserver"]}],"hierarchy":{"paths":[[]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/StubResponse","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/StubServer","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/UITestResponse"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerDelegate"],"anchor":"Protocols","title":"Protocols"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/UITestServer"],"anchor":"Structures","title":"Structures"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerName","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerVersion"],"anchor":"Variables","title":"Variables"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/RouteHandler"],"anchor":"Type-Aliases","title":"Type Aliases"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/HTTPMethod"],"anchor":"Enumerations","title":"Enumerations"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/Foundation"],"anchor":"Extended-Modules","title":"Extended Modules"}],"metadata":{"roleHeading":"Framework","title":"LocalServer","symbolKind":"module","role":"collection","externalID":"LocalServer","modules":[{"name":"LocalServer"}]},"references":{"doc://org.cocoapods.LocalServer/documentation/LocalServer/HTTPMethod":{"title":"HTTPMethod","url":"\/documentation\/localserver\/httpmethod","kind":"symbol","abstract":[{"type":"text","text":"The HTTP Methods as per W3C consortium standards."},{"text":" ","type":"text"},{"text":"https:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec9.html","type":"text"}],"navigatorTitle":[{"text":"HTTPMethod","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/HTTPMethod","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTTPMethod"}]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/kLocalServerName":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLocalServerName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerName","role":"symbol","type":"topic","kind":"symbol","title":"kLocalServerName","navigatorTitle":[{"kind":"identifier","text":"kLocalServerName"}],"url":"\/documentation\/localserver\/klocalservername"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/LocalServerDelegate":{"url":"\/documentation\/localserver\/localserverdelegate","title":"LocalServerDelegate","abstract":[{"text":"Defines the necessary methods to become a LocalServer responder.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalServerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"LocalServerDelegate"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerDelegate","kind":"symbol","type":"topic"},"doc://org.cocoapods.LocalServer/documentation/LocalServer":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer","kind":"symbol","abstract":[],"url":"\/documentation\/localserver","type":"topic","title":"LocalServer","role":"collection"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/LocalServerVersionString":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerVersionString","type":"topic","fragments":[{"text":"LocalServerVersionString","kind":"identifier"}],"title":"LocalServerVersionString","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/localserver\/localserverversionstring"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/LocalServerVersionNumber":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerVersionNumber","url":"\/documentation\/localserver\/localserverversionnumber","type":"topic","kind":"symbol","title":"LocalServerVersionNumber","role":"symbol","fragments":[{"kind":"identifier","text":"LocalServerVersionNumber"}]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/RouteHandler":{"title":"RouteHandler","navigatorTitle":[{"kind":"identifier","text":"RouteHandler"}],"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/RouteHandler","url":"\/documentation\/localserver\/routehandler","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteHandler"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The closure format containg Request and the query parameters for a given URL"}]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/Foundation":{"title":"Foundation","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/Foundation","url":"\/documentation\/localserver\/foundation","role":"collection","type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/StubResponse":{"title":"StubResponse","url":"\/documentation\/localserver\/stubresponse","abstract":[{"type":"codeVoice","code":"StubResponse"},{"type":"text","text":" is the base response to simulate "},{"type":"codeVoice","code":"URLResponses"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It defines the HTTP Status code, the Responder Header and Body."},{"type":"text","text":" "},{"type":"text","text":"It can also define a delay in seconds, simulating delayed server responses."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StubResponse","kind":"identifier"}],"navigatorTitle":[{"text":"StubResponse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/StubResponse","kind":"symbol","type":"topic"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/StubServer":{"title":"StubServer","abstract":[{"type":"text","text":"Defines the main Stub Server object. It can be subclassed to provide various other types"},{"type":"text","text":" "},{"type":"text","text":"of local server."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StubServer","kind":"identifier"}],"navigatorTitle":[{"text":"StubServer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/StubServer","type":"topic","url":"\/documentation\/localserver\/stubserver"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/UITestServer":{"kind":"symbol","navigatorTitle":[{"text":"UITestServer","kind":"identifier"}],"role":"symbol","title":"UITestServer","url":"\/documentation\/localserver\/uitestserver","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITestServer","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/UITestServer","abstract":[{"text":"This is the base for the UITest Local Server and it works in conjunction with ","type":"text"},{"type":"codeVoice","code":"UITestResponse"},{"type":"text","text":" "},{"text":"It’s able to provide a bridge between UITest and the main application.","type":"text"}]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/kLocalServerVersion":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerVersion","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLocalServerVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"kLocalServerVersion","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/localserver\/klocalserverversion","navigatorTitle":[{"text":"kLocalServerVersion","kind":"identifier"}]},"doc://org.cocoapods.LocalServer/documentation/LocalServer/UITestResponse":{"type":"topic","title":"UITestResponse","url":"\/documentation\/localserver\/uitestresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITestResponse"}],"navigatorTitle":[{"kind":"identifier","text":"UITestResponse"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/UITestResponse","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UITestResponse"},{"text":" is the base response for ","type":"text"},{"code":"UITestServer","type":"codeVoice"},{"type":"text","text":". It contains methods to send"},{"type":"text","text":" "},{"type":"text","text":"the response data to the Local Server."},{"type":"text","text":" "},{"type":"text","text":"This type also provides support to the concept of states for simulating Stateful behaviors"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Variables","identifiers":["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerVersionNumber","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/LocalServerVersionString","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerName","doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerVersion"],"anchor":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerName\/title","value":"kLocalServerName"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerName\/fragments","value":[{"kind":"identifier","text":"kLocalServerName"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerVersion\/title","value":"kLocalServerVersion"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerVersion\/fragments","value":[{"text":"kLocalServerVersion","kind":"identifier"}]}]}]}