{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/localserver\/klocalserverversion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/localserver\/klocalserverversion"]}],"metadata":{"modules":[{"name":"LocalServer"}],"navigatorTitle":[{"text":"kLocalServerVersion","kind":"identifier"}],"role":"symbol","title":"kLocalServerVersion","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLocalServerVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"var","externalID":"c:LocalServer.h@kLocalServerVersion","roleHeading":"Global Variable"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLocalServerVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerVersion","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.LocalServer/documentation/LocalServer":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer","kind":"symbol","abstract":[],"url":"\/documentation\/localserver","type":"topic","title":"LocalServer","role":"collection"},"doc://org.cocoapods.LocalServer/documentation/LocalServer/kLocalServerVersion":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerVersion","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLocalServerVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"kLocalServerVersion","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/localserver\/klocalserverversion","navigatorTitle":[{"text":"kLocalServerVersion","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"kLocalServerVersion","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"kLocalServerVersion"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"kLocalServerVersion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"kLocalServerVersion","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerVersion\/title","op":"replace"},{"value":[{"kind":"identifier","text":"kLocalServerVersion"}],"path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerVersion\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}