{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLocalServerName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Global Variable","modules":[{"name":"LocalServer"}],"externalID":"c:LocalServer.h@kLocalServerName","title":"kLocalServerName","symbolKind":"var","navigatorTitle":[{"text":"kLocalServerName","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/localserver\/klocalservername"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/localserver\/klocalservername"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerName","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLocalServerName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.LocalServer/documentation/LocalServer/kLocalServerName":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLocalServerName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer\/kLocalServerName","role":"symbol","type":"topic","kind":"symbol","title":"kLocalServerName","navigatorTitle":[{"kind":"identifier","text":"kLocalServerName"}],"url":"\/documentation\/localserver\/klocalservername"},"doc://org.cocoapods.LocalServer/documentation/LocalServer":{"identifier":"doc:\/\/org.cocoapods.LocalServer\/documentation\/LocalServer","kind":"symbol","abstract":[],"url":"\/documentation\/localserver","type":"topic","title":"LocalServer","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"kLocalServerName","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"kLocalServerName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLocalServerName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"kLocalServerName","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerName\/title"},{"value":[{"kind":"identifier","text":"kLocalServerName"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LocalServer~1documentation~1LocalServer~1kLocalServerName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}